language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install pytest-cov
  - pip3 install pytest


# command to run tests
script:
  - pytest
  - pytest --cov=api
  #- echo "todo"

after_success:
  coveralls

# Come 
