language: python
python:
  - "2.7"


install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov


# command to run tests
script:

 - python test_user.py
 - pytest --cov =./
 - echo "todo"

 after-success:
  - coveralls